### ISSUE TITLE
redirect error (unknown path)

### ISSUE THREAD

**Issue by AlberErre** [lluisrojass/Tumblr-Post-Scraper#3]
I'm trying to reproduce your example on MacOS (Mojave) and it doesn't work at all, it always returns `redirect error (unknown path)` - any thoughts?

I have attached a screenshot.

![captura de pantalla 2018-11-20 a las 1 23 08](https://user-images.githubusercontent.com/20255458/48745309-ddfb8a80-ec62-11e8-9334-aac41471711b.png)

Thank you!

Cheers

**Comment by lluisrojass** [comment]
@AlberErre I'm aware of a bug that precludes future scrapes after the app encounters one which redirects. I'm currently in the process of re-building the application and this bug will be fixed, Can you tell me if your issue happens upon cold boot?

**Comment by AlberErre** [comment]
Hey @lluisrojass , yes it happens upon cold boot. I have tried both, using your released `.dmg` image and building my own from source code using ` npm install --> npm run build-osx `.

Probably the issue is related to Tumblr too, as they have several issues at the moment. 

Cheers!

**Comment by lluisrojass** [comment]
@AlberErre going to keep this open in case anyone else is experiencing this. Currently, this message is shot out when you receive a 302, 303 and 307 response. The requests loop starts out as http and if a 302, 303 or 307 is initially recieved, we upgrade to https and try again. If at that point we still get one of these messages, then this error is shot out. It's possible something unique to your geographical situation or your added code is causing a double 302 prematurely or by accident. Please don't hesitate to comment anything else you want to contribute to this.

**Comment by pasky** [comment]
This issues happen to me as well, with a fresh install on macos, from within the EU (where we get a privacy notice first when accessing tumlr).
